name: Deploy Package

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Python package
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install twine
          python setup.py sdist bdist_wheel
          cd ..

      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
